# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uj0dxWpZv-DaAmOFfg8S7-4xFiOajyXA
"""

# ques 4
import pandas as pd
stu=({"name":["moni","caramel","alpha","krsna","nisha","inom","krishna","pa","sat","zen"],
      "age":[20,21,21,22,23,22,21,20,24,22],
      "dob":[2002,2001,2001,2000,1999,2000,2001,2002,1998,1999],
      "weight":[50,55,49,60,54,45,59,40,50,49],
      "height":[1.54,1.52,1.50,1.60,1.62,1.59,1.57,1.59,1.50,1.47]})
df=pd.DataFrame(stu)
df["BMI"]=round(df["weight"]/stu["height"])
df["status"]=df["BMI"].map(lambda x:"Healthy" if x in range(0, 35) else  "Overweight")
print(df)

#ques 5
bill=int(input("enter units used:"))
if bill == 0 and bill < 100:
  print("units consumed=",bill,"unit amount=Rs 0.50/unit:",round(0.50*bill))
elif bill >= 100 and bill <= 200:
  print("units consumed=",bill,"unit amount=Rs 0.75/unit:",round(0.75*bill))
elif bill >= 200 and bill <= 300:
  print("units consumed=",bill,"unit amount=Rs 1.20/unit:",round(1.20*bill))
else :
  print("units consumed=",bill,"unit amount=Rs 1.50/unit:",round(1.50*bill))

#ques 2
amt=123000
print("total amount paid : ,123000")
print("gst percentage: 18%")
gst=(123000 * (18/100)) 
print("gst paid in amount:",gst)
print("net price :",gst-amt)

mal={"trojan":"stealthy impersonate","virus":"replicates","worm":"finds vulnerability"}
print(mal)
print(mal.get("trojan"))
print(mal.keys())
print(mal.pop("worm"))
print(mal.items())

#ques1
print("","I am signing up for Replit&#39;s 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I&#39;ll be usingReplit, an amazing online IDE so I can do this from my phone wherever I happend to be. No excuses for not coding from the middle of a field!")